### ISSUE TITLE
Fail on JDK8

### ISSUE THREAD

**Issue by ericdallo** [IGJoshua/americano#1]
Hi, aweomse project!

I configured it on [clojure-lsp](https://clojure-lsp.github.io/clojure-lsp/), but it failed on CI only for java8: https://github.com/clojure-lsp/clojure-lsp/runs/2590947200?check_suite_focus=true

```
Execution error (IllegalStateException) at com.sun.tools.javac.main.Main/error (Main.java:186).
directory not found: classes
```

This is the relevant commit that added americano: https://github.com/clojure-lsp/clojure-lsp/commit/b55e964eaa9c6677570f04f68ee20b414f830a7f

**Comment by IGJoshua** [comment]
Oh this is interesting! I think this can be solved pretty easily, the problem is that under later versions the toolchain automatically creates the directory for the class files. I'll push a hotfix that manually creates the directory to ensure it doesn't fail on java8. Thanks for the report!

**Comment by IGJoshua** [comment]
@ericdallo Can you re-test with a git dependency on this commit `bceafd260c948cc758ca85b2ff82180b2a775d47` just to validate it works before I push it to clojars?

**Comment by ericdallo** [comment]
It fixes it 🎉 
https://github.com/clojure-lsp/clojure-lsp/pull/427

**Comment by IGJoshua** [comment]
Awesome, I'll publish a hotfix release then.

**Comment by IGJoshua** [comment]
Version 1.0.1 has been published on clojars!
